services:

  frontend:
    build:
      context: ./frontend  # ระบุ context สำหรับการ build
      dockerfile: Dockerfile  # ใช้ Dockerfile ที่กำหนด
    environment:
      - REACT_APP_INVENTORY_BASE_URL=${REACT_APP_INVENTORY_BASE_URL}
      - REACT_APP_SUPPLIER_BASE_URL=${REACT_APP_SUPPLIER_BASE_URL}
      - REACT_APP_PURCHASE_ORDER_BASE_URL=${REACT_APP_PURCHASE_ORDER_BASE_URL}
    # ไม่ควรใช้ volume mapping ใน production
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    env_file:
      - .env.production  # โหลด environment variables จากไฟล์ .env.production
    ports:
      - "3000:3000"  # เปิดพอร์ต 3000
    depends_on:
      - loyverse-connect  # รอให้ backend พร้อมใช้งาน

  loyverse-connect:
    build:
      context: . 
      dockerfile: backend/external/loyverse/Dockerfile  # ระบุ Dockerfile โดยตรง
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - LOYVERSE_API_TOKEN=${LOYVERSE_API_TOKEN}
    env_file:
      - .env.production  # โหลด environment variables จากไฟล์ .env.production
    ports:
      - "8080:8080"
    depends_on:
      # db:
      #   condition: service_healthy
      - db

  inventory-management:
    build:
      context: . 
      dockerfile: backend/internal/InventoryManagement/Dockerfile  # ระบุ Dockerfile โดยตรง
    environment:
      - DATABASE_URL=${DATABASE_URL}
      # - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json 
      - GCP_PROJECT_ID=ynabim  # ใส่ชื่อ project ของคุณ
      - GOOGLE_SHEETS_SPREADSHEET_ID=${GOOGLE_SHEETS_SPREADSHEET_ID}
      - GOOGLE_CLOUD_PROJECT=ynabim

    env_file:
      - .env.production  # โหลด environment variables จากไฟล์ .env.production
    ports:
      - "8082:8082"
    
    # volumes:
      # - ./backend/internal/InventoryManagement/credentials.json:/root/credentials.json

    depends_on:
      # db:
      #   condition: service_healthy
      - db
  
  supplier-management:
    build:
      context: .
      dockerfile: backend/internal/SupplierManagement/Dockerfile
    container_name: supplier-management
    environment:
      - PORT=8083
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env.production  # โหลด environment variables จากไฟล์ .env.production
    ports:
      - "8083:8083"
    depends_on:
      - db

  sale-management:
    build:
      context: .
      dockerfile: backend/internal/SaleManagement/Dockerfile
    container_name: sale-management
    environment:
      - PORT=8084
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env.production  # โหลด environment variables จากไฟล์ .env.production
    ports:
      - "8084:8084"
    depends_on:
      - db
  db:
    image: postgres:13  # ใช้ image ของ PostgreSQL เวอร์ชัน 13
    environment:
      POSTGRES_USER: loyuser  # กำหนดผู้ใช้ฐานข้อมูล
      POSTGRES_PASSWORD: password  # กำหนดรหัสผ่าน 
      POSTGRES_DB: loyverse_cache  # กำหนดชื่อฐานข้อมูล
    env_file:
      - .env.production  # โหลด environment variables จากไฟล์ .env.production
    ports:
      - "5433:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U loyuseraa"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data  # กำหนด volume สำหรับข้อมูล

volumes:
  postgres_data: {}  # กำหนด volume สำหรับ PostgreSQL

